void rightRotate( TreeNode *x, TreeNode **root );
void  leftRotate( TreeNode *x, TreeNode **root );
void InsertNode( TreeNode **root, int key );
void deleteNode( TreeNode **root, int key );
TreeNode* allocateNewNode( TreeNode **parent, int key, bool color, int left_root_right );
void printInorder( TreeNode *node );
TreeNode* inorderSuccessor( TreeNode *node );
bool validateBST(TreeNode* node, TreeNode* prev);
bool isValidBST(TreeNode* root);
bool isBalanced(TreeNode *root);
void print2D( TreeNode* root);
bool isLeftChild( TreeNode * node );
TreeNode* searchNode( TreeNode *root, int key );
void DeallocateTree ( TreeNode **node );
